#!/bin/bash

# This script provides a menu for activating a virtual environment. You need to
# copy it (or an alias to it) to /usr/local/bin. To invoke this script, type 
#
#     source $(pve)
#
# from the command line.

PS3="Choose an environment: "

folders=$(find ~/pve/. -type d -maxdepth 1 | sort -f | sed -E 's/(.+)\/(.+$)/\2/')

select folder in ${folders[@]:1};
do
    echo ~/pve/$folder/bin/activate
    break;
done
